export const doctorsData = [
  {
    name: 'Dr. John Doe',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: require('./src/images/doctors-image/doctor1-icon.png'),
    consultationCharge: 100,
    hospital: 'City Hospital',
    yearsOfPractice: 15,
    details:
      'Expert in treating heart-related conditions, including hypertension and heart failure.',
  },
  {
    name: 'Dr. Sarah Johnson',
    specialty: 'Dermatologist',
    rating: 4.7,
    image: require('./src/images/doctors-image/doctor2-icon.png'),
    consultationCharge: 80,
    hospital: 'Skin Care Clinic',
    yearsOfPractice: 10,
    details:
      'Specializes in skin care treatments, acne management, and cosmetic dermatology.',
  },
  {
    name: 'Dr. Michael Brown',
    specialty: 'Orthopedic Surgeon',
    rating: 4.9,
    image: require('./src/images/doctors-image/doctor2-icon.png'),
    consultationCharge: 120,
    hospital: 'Orthopedic Institute',
    yearsOfPractice: 12,
    details: 'Expert in joint replacement, sports injuries, and trauma care.',
  },
  {
    name: 'Dr. Emily Davis',
    specialty: 'Pediatrician',
    rating: 4.6,
    image: require('./src/images/doctors-image/doctor1-icon.png'),
    consultationCharge: 90,
    hospital: 'Children’s Hospital',
    yearsOfPractice: 8,
    details:
      'Specializes in child health care, immunization, and growth monitoring.',
  },
  {
    name: 'Dr. Richard Wilson',
    specialty: 'Neurologist',
    rating: 4.5,
    image: require('./src/images/doctors-image/doctor2-icon.png'),
    consultationCharge: 130,
    hospital: 'Neuro Care Center',
    yearsOfPractice: 14,
    details:
      'Experienced in treating neurological disorders, including epilepsy and migraines.',
  },
  {
    name: 'Dr. Laura Martinez',
    specialty: 'Gynecologist',
    rating: 4.8,
    image: require('./src/images/doctors-image/doctor1-icon.png'),
    consultationCharge: 110,
    hospital: 'Women’s Health Clinic',
    yearsOfPractice: 11,
    details:
      'Specializes in women’s health, prenatal care, and fertility treatments.',
  },
  {
    name: 'Dr. David Lee',
    specialty: 'Psychiatrist',
    rating: 4.7,
    image: require('./src/images/doctors-image/doctor1-icon.png'),
    consultationCharge: 95,
    hospital: 'Mental Health Center',
    yearsOfPractice: 9,
    details:
      'Expert in treating mental health issues, including depression and anxiety.',
  },
  {
    name: 'Dr. Lisa White',
    specialty: 'Endocrinologist',
    rating: 4.9,
    image: require('./src/images/doctors-image/doctor2-icon.png'),
    consultationCharge: 115,
    hospital: 'Endocrine Clinic',
    yearsOfPractice: 13,
    details:
      'Specializes in hormone-related disorders, including diabetes and thyroid problems.',
  },
  {
    name: 'Dr. James Clark',
    specialty: 'Oncologist',
    rating: 4.6,
    image: require('./src/images/doctors-image/doctor1-icon.png'),
    consultationCharge: 140,
    hospital: 'Cancer Care Institute',
    yearsOfPractice: 16,
    details:
      'Experienced in cancer treatment, including chemotherapy and radiation therapy.',
  },
  {
    name: 'Dr. Olivia Lewis',
    specialty: 'Ophthalmologist',
    rating: 4.7,
    image: require('./src/images/doctors-image/doctor1-icon.png'),
    consultationCharge: 85,
    hospital: 'Eye Care Hospital',
    yearsOfPractice: 10,
    details:
      'Specializes in eye care, cataract surgery, and vision correction.',
  },
  {
    name: 'Dr. Robert Walker',
    specialty: 'Gastroenterologist',
    rating: 4.8,
    image: require('./src/images/doctors-image/doctor1-icon.png'),
    consultationCharge: 105,
    hospital: 'Digestive Health Clinic',
    yearsOfPractice: 12,
    details:
      'Expert in treating digestive disorders, including IBS and liver disease.',
  },
  {
    name: 'Dr. Sophia Harris',
    specialty: 'Pulmonologist',
    rating: 4.6,
    image: require('./src/images/doctors-image/doctor2-icon.png'),
    consultationCharge: 110,
    hospital: 'Lung Health Center',
    yearsOfPractice: 14,
    details:
      'Specializes in respiratory conditions, including asthma and COPD.',
  },
];
